export const Selectors = {
  breadCrumb: ".Breadcrumb_breadcrumb__current_text__26lCj",
  threeDotsMenu: ".css-q34dxg",
  firstUnit: ".css-1liixou",
  title: ".DetailInfo_profile__info__title__2XtbT",
  subTitle: ".DetailInfo_profile__info__desc__U6qdb",
  secondSubTitle: ".DetailInfo_profile__info__driver__3hWmx",
  detailInfoBox: ".DetailField_data__bOXlw",
  commentField: '[placeholder="Add a comment"]',
  addCommentButton: ".MuiButton-contained",
  delete: "Delete",
  threeDotsMenu: ".css-1yxmbwk",
  titleUserComment: ".CommentItem_comment__name__E9dc2",
  beVisible: "be.visible",
  haveText: "have.text",
  optionUnits: ".css-19bb58m",
  selectUnit: ".css-p7gue6-option",
  unassigned: ".ItemCard_button__LMaiC",
  linkedVehiclesList: ".ItemCard_item_card__content__title__t740I",
  linkAssets: ".SectionCard_section_card__header__button_cont__button__EjwCb",
  breadCrumbBack: ".MuiBreadcrumbs-li",
};
